// src/shades.js
export const shades = [
  { id: 0, url: "/shade1.jpg" },
  { id: 1, url: "/shade2.jpg" },
  { id: 2, url: "/shade3.jpg" },
  { id: 3, url: "/shade4.jpg" },
  { id: 4, url: "/shade5.jpg" },
  { id: 5, url: "/shade6.jpg" },
  { id: 6, url: "/shade7.jpg" },
  { id: 7, url: "/shade8.jpg" },
  { id: 8, url: "/shade9.jpg" },
  { id: 9, url: "/shade10.jpg" },
  { id: 10, url: "/shade11.jpg" },
  { id: 11, url: "/shade12.jpg" },
  { id: 12, url: "/shade13.jpg" },
  { id: 13, url: "/shade14.jpg" },
  { id: 14, url: "/shade15.jpg" },
  { id: 15, url: "/shade16.jpg" },
  // { id: 16, url: "/shade17.jpg" },
];
